global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  # Point to the so-called “dynamic” configuration, managed by
  # Ansible
  file:
    directory: /etc/traefik/dynamic
    watch: true
  # Additionally, read Docker container labels as a dynamic configuration source.
  docker:
    exposedByDefault: false

{% if traefik_debug %}
log:
  level: DEBUG
{% endif %}

api:
  dashboard: true

metrics:
  prometheus:
    entryPoint: websecure

# https://docs.traefik.io/https/acme/
certificatesResolvers:
  letsencrypt:
    acme:
{% if traefik_letsencrypt_staging is defined %}
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
{% endif %}
      storage: /acme/acme.json
      email: idev-fsd@groupes.epfl.ch
      tlsChallenge: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - {{ frontend.domain }}


