access_admin_accounts:
  - github: domq       # Dominique Quatravaux
  - github: ponsfrilus # Nicolas Borboën
  - github: multiscan  # Giovanni Cangiani
  - github: jdelasoie  # Julien Delasoie
  - github: lvenries   # Luc Venries
  - github: dwesh163   # Ehouarn Duriaux
  - github: xpl0z      # Ménélik Siegrist
